[build]
  publish = "public"
  command = "composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache && npm ci && npm run build"

[build.environment]
  PHP_VERSION = "8.2"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[context.production.environment]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_LEVEL = "error"

[context.deploy-preview.environment]
  APP_ENV = "staging"
  APP_DEBUG = "true"
